language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_ConfigDotEnv
  - secure: A6PbR9S2HdQU4WNDnZTwWfL6mCTVeYvGzo0FFvxgREk0+6dtPLizmpjo8McVlhx/6hrGdPlHDfCq9+nUEX2UpkkxLBHuxNFa5OW63MJyTMShH2I4LJL7o2GOWNxfwW8FTLzjk0oL9JBp5ikZ1UVUznVfUQIXXuyUz75E9WUKavFzrVMsEZOs9ZMGXseIDh0ZDlGLarDF5Yr7TUAbEBS/y1p11e+1t397lq12bD84tvL1Q+wW6IYhdCQOnCpDMnSWzT8LOUWC3EqOFKChMgKlhKZTVingHlal8QDd3ZFVnpL1OSw/5AjBQnDmQNAdG74a+AZS4Yr0WRdHj5GiGN08RsQ6TH014PYuh7Q4GkMw13QhnHjt7zdO1YkQzugcybQXjI74dKmlt91ZW+RPl+jdfmcCb3144S7Akcz3fJ6EGfuF3LP2VNoGR2Dj5k8aonuRpnbZD5zhg4+ZmMlW4D/QdSOR7NLfis36+GGQI4H0w+NQ7QYRrc8y0qTgLg7BM1DlTLgVKgVPFEhONSHwwwKzP/ZLNSqoEGRGYf3Jk1duTHWFaDFngT9gGX5VB1L7BQVCTEZqNtaQlFkyfSsHaGutavXNcjj2futiYl7gDt2PiYlwk/vBWSoopL8HdNuKIrcy+sC8RTl1Ti2EMsrBZ5UnVqian1lDrfd5rLLY/HnBVcw=
  - secure: TIZ7oqEXlFudb4N1Igl6Sx4YUMIw0i+OeYi7lc1bEFj6TdEDwmwlFS+lQDoPccX6XajUdefdKfrPK/eX/TMnwWq6flgjlgmUVSLsqAlKEtGuY+kQkSDTYaweu5V94EEwvEZqaMztQsgF/NrwTKbooHIxQNp0oPtOuTRA+/kNRUFTZL//GiA6L4FJg2/TrLtW/lbzTcq2qe9J9K0SvYtFAnJRjxdiTRwI6Xrl06ZDOULmBFUIt1yK5QFQNxybTWosAbPtkNVUyhZxCkAqgfQN/fl8ffc02GXyYNNCE1o4eNSWFFverw+72c4AWDF3O7WEFF9htYHowQ9z3SNAn7pvqOOpHkiTb+Pi3JvvFg8ZgcMXgZAvnLcMVlBxdiq2GFZxCH8LSD+cIwMh50OPxJYLU54jkUMSQDaxdYk/cuOIqSSMVCTvHH/gMKu3cZ7GpX1g4OesI93pq7Bv5JWuQ5YCi6Agco19EwPsOjip0fnrX8wCeVlijH4QaSmkbuU1fM5X0e3Cp0D+MTAoqleMqhpEeIvsEOYtgB+PEOWmUyIXz2XJZ9U4FFSU/1LW2TElRJdK+Y5eWnjDssK1jKT/sqgfDoibKHWlV+O4DSFdbRKMAFDSWmyfEdxVc6d0zshmvUGUVLRZW39iZfCIDC21VRnghYhZfjWNPg57Zdnd8Um7CIM=
  - secure: eSyMh6N0jl9qvtR8XiF56PlrON5k010Gie0QQNZzQb7M+SRfH6pkmkAmEzOvvv6mhpvAoJCF9Sc280FHfGBpx83FmbQxouH0bLK6t4vugn1FLPmigG/nN3W0xIl37AMRlOkLMQAyJQRTh8qyOJyyZkgPi1a1JMRYdeFDrrE678dwlYxEdbPRjJH1Wl94zjnGcP0LlH3sXnDHAQv7+/EUzHV1LI/HPtDc/JtNhczGYMP7/Vs5GHucSisXVowMDiNL7F/NHazsCp/voq1NgzeDY9A6tKC3wJ+njSdvBUBon4UEF/qUXlqbLqmhgdgsnID2o1y5L+4tWVMiVFWLbqmyxXlA1dnaaQC02XKR3axXZFBBn7/HjofpoWJHCG+DQbJx+h+PjFxsXmGm1SIKiuguCW6do/LhbcTjOos4umfy5sK7hSytjiHbXQvdHAo1f0uFKejDwfMKxTVk72exyttVG/CWFFc/J7LhG1SnHbNrtnwwcs8wtkOeDHi03VptTCrh0JH0CWH/vmuU+WqNzewk4epdQqKG3z1amtCKVIiu4L2IbuiWONOhfdHUfVXa/5VnB9NdY5WrVV18+WoyhxArWqibSzjiMz63RcedQFJyncJ20ZHNsHFzWQyxSbYZVeMJfWzrBT6SapjCZy1APLudhNIYMB3Mn/GUcaU96ib2btU=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: d8hXhpQYkVYEoffKsDHjND4onJHdM9O2oXJLfru3MNRYSqq/Qnle3EGp8jOBBfULN6PMq5z62Lx7EYrbvb4ltKLBQaKRnHTqHS1LrzMh+Gvir4Avwkj8PrIj+VQ13sL3gzx2hrnPoeH4txHoRxnkuLXzHyfYmPrQkAnip41ttBXYDBKxycD868MflS3etN2uyUqX2tKCYZsckOneuecL0ph65iKDe0dF4Pw7ObpZ68uIQ6P6ts0uZZdrbCeK+fLIg2XEEmp8GKL1xGhQeVabBolWOjyrFvTSDwC8ZTID5azhzsQYjasAt5OejQ8pjXOW2FMSJXpiKLGxJD9JY9EJn3fydTWu5+LGjo0jZIPLT0ZYJElTt+2RNd23D8DaHyWdZLqEGubV+ZH+Rjfbtwwo9sWNDyeFqguzePgXJc1Wuaox2ORTps4V2yzx1Z17BTze5mv5jYrwQwldAuIEW90rFvHzFWov7vzW7+Kv0KzuzfjHDF+dj0jv5EbsHoCD5dDZqgl8FcOeFn1q3fEohdWMcuuMui5J8wp1xx/bVBx6TmXP6tw5xdU2NcZD7i3FV5+3Q2L7BzJEUXnuDCAjlFr3uqYWpG7tUed8AsOn8T0RrcTiRZqcnjrG9PZz0uWEDKRBvzAi3/NdxaxDGVuTVHKAzQ5o3Sc6Ry4nUXcKoWEgqK8=
notifications:
  slack:
    secure: T3NtfOZp/JXbcyuW1aHllYgb52o/f5qqriDX++0J7Dk54zI8wp1HS6pvYskQNiplQP6w4yBG4+aOIzc+d30FxD7Ihd0BYBsv9xP7CEeE42fht0rvMbTRTnwkIpVZvnTDSra3VTzebT9+2tYC1UtcBs3G43lJfmSH2jT1cmI1qfqD1xHSVUfDKZl4160xl/1DKzfUCkib0W3XIbgKAVTsNG5VpOlxYRRRfwSGXLH8bzdbMi655oslCLtqeYhJrPOavf2oXETxgJiB3VmyUQLbVqY3JIJcY/eLby75hIaRGX1U8Kh+XagQCgsJmSTh0JpYj4oD7LIl4j+kRQ7IDl1rIOXypbjuI8U3Q10awQHGGhsjdZIPnjJqw92gWPVUqFKf9FTAoou3ASOihte0ZzNzsvLgHgWi7oKq6T6gPI0WdoEtz0YqDHftp3NNgVenZrbccmUXtNWD+l8O5jsJihOBjGfeCrJi2rcIL1w1zp1hSZwGM5s4rrKrVfgdixv9tjbm281K89+9dSXPPPjt50qFjeemzhwC6ttXmXkhC56YkkBgmystDzJnzybX1ZXFKn54yMjsRlHLD5R1lkkZ0+aIW5yIIUiWeYVPaCIfk3+dEza4IaNW7u+njh1I0Co8K1bMOnpl/mPxsetnp8KQxfbJL+p+YRnCFVHTsKkjqkSFZLA=
